# This file is part of Fumoco.
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Holger Peters -- see the LICENSE file.

name: CI

on:
  push:
    branches:
    - main
    - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-26.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7
    - name: Install Node
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: npm
    - name: Install Dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-26.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v7
    - name: Install Node
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: npm
    - name: Install Dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
